name: Deploy to Oracle Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Node.js Backend
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: opc
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /home/opc/nodejs-backend
            git pull origin main
            npm install
            pm2 restart nodejs-backend
